use crate::{
    fen_parser::{BLACK, WHITE},
    game::{MailBoxBoard, Piece},
};

pub const STARTING_BOARD: MailBoxBoard = [
    [
        Piece::Rook(BLACK),
        Piece::Knight(BLACK),
        Piece::Bishop(BLACK),
        Piece::Queen(BLACK),
        Piece::King(BLACK),
        Piece::Bishop(BLACK),
        Piece::Knight(BLACK),
        Piece::Rook(BLACK),
    ],
    [Piece::Pawn(BLACK); 8],
    [Piece::Empty; 8],
    [Piece::Empty; 8],
    [Piece::Empty; 8],
    [Piece::Empty; 8],
    [Piece::Pawn(WHITE); 8],
    [
        Piece::Rook(WHITE),
        Piece::Knight(WHITE),
        Piece::Bishop(WHITE),
        Piece::Queen(WHITE),
        Piece::King(WHITE),
        Piece::Bishop(WHITE),
        Piece::Knight(WHITE),
        Piece::Rook(WHITE),
    ],
];

pub const BOARD2: MailBoxBoard = [
    [Piece::Empty; 8],
    [
        Piece::Empty,
        Piece::Empty,
        Piece::Empty,
        Piece::Empty,
        Piece::Empty,
        Piece::King(BLACK),
        Piece::Empty,
        Piece::Empty,
    ],
    [
        Piece::Empty,
        Piece::Empty,
        Piece::Empty,
        Piece::Pawn(BLACK),
        Piece::Empty,
        Piece::Empty,
        Piece::Empty,
        Piece::Empty,
    ],
    [
        Piece::Empty,
        Piece::Pawn(BLACK),
        Piece::Empty,
        Piece::Pawn(WHITE),
        Piece::Pawn(BLACK),
        Piece::Empty,
        Piece::Empty,
        Piece::Pawn(BLACK),
    ],
    [
        Piece::Pawn(BLACK),
        Piece::Pawn(WHITE),
        Piece::Empty,
        Piece::Empty,
        Piece::Pawn(WHITE),
        Piece::Pawn(BLACK),
        Piece::Empty,
        Piece::Pawn(WHITE),
    ],
    [
        Piece::Pawn(WHITE),
        Piece::Empty,
        Piece::Empty,
        Piece::Empty,
        Piece::Empty,
        Piece::Pawn(WHITE),
        Piece::Empty,
        Piece::King(WHITE),
    ],
    [Piece::Empty; 8],
    [Piece::Empty; 8],
];

pub const BOARD3: MailBoxBoard = [
    [
        Piece::Rook(BLACK),
        Piece::Empty,
        Piece::Bishop(BLACK),
        Piece::King(BLACK),
        Piece::Empty,
        Piece::Empty,
        Piece::Empty,
        Piece::Rook(BLACK),
    ],
    [
        Piece::Pawn(BLACK),
        Piece::Empty,
        Piece::Empty,
        Piece::Pawn(BLACK),
        Piece::Bishop(WHITE),
        Piece::Pawn(BLACK),
        Piece::Knight(WHITE),
        Piece::Pawn(BLACK),
    ],
    [
        Piece::Knight(BLACK),
        Piece::Empty,
        Piece::Empty,
        Piece::Empty,
        Piece::Empty,
        Piece::Knight(BLACK),
        Piece::Empty,
        Piece::Empty,
    ],
    [
        Piece::Empty,
        Piece::Pawn(BLACK),
        Piece::Empty,
        Piece::Knight(WHITE),
        Piece::Pawn(WHITE),
        Piece::Empty,
        Piece::Empty,
        Piece::Pawn(WHITE),
    ],
    [
        Piece::Empty,
        Piece::Empty,
        Piece::Empty,
        Piece::Empty,
        Piece::Empty,
        Piece::Empty,
        Piece::Pawn(WHITE),
        Piece::Empty,
    ],
    [
        Piece::Empty,
        Piece::Empty,
        Piece::Empty,
        Piece::Pawn(WHITE),
        Piece::Empty,
        Piece::Empty,
        Piece::Empty,
        Piece::Empty,
    ],
    [
        Piece::Pawn(WHITE),
        Piece::Empty,
        Piece::Pawn(WHITE),
        Piece::Empty,
        Piece::King(WHITE),
        Piece::Empty,
        Piece::Empty,
        Piece::Empty,
    ],
    [
        Piece::Queen(BLACK),
        Piece::Empty,
        Piece::Empty,
        Piece::Empty,
        Piece::Empty,
        Piece::Empty,
        Piece::Bishop(BLACK),
        Piece::Empty,
    ],
];
